@startuml casos_de_uso
left to right direction
skinparam packageStyle rectangle

actor Aluno
actor Bibliotecario as "Bibliotecário"

rectangle "Sistema de Gestão de eBooks" {
  usecase "Realizar login" as UC01
  usecase "Adicionar eBook à estante" as UC02
  usecase "Remover eBook da estante" as UC03
  usecase "Consultar estante pessoal" as UC04
  usecase "Consultar alunos com um eBook" as UC05
  usecase "Cadastrar eBook" as UC06
}

Aluno --> UC02 : UC02
Aluno --> UC03 : UC03
Aluno --> UC04 : UC04

Bibliotecario --> UC05 : UC05
Bibliotecario --> UC06 : UC06

UC02 ..> UC01 : <<include>>\n(UC01)
UC03 ..> UC01 : <<include>>\n(UC01)
UC04 ..> UC01 : <<include>>\n(UC01)
UC05 ..> UC01 : <<include>>\n(UC01)
UC06 ..> UC01 : <<include>>\n(UC01)
@enduml
